uc-cdis/mc2dp-data-platform

- config/gen3/landingPage.json
Link to JIRA ticket if there is one: [PROM-25](https://ctds-planx.atlassian.net/browse/PROM-25)
* change the description on the home page
[PROM-25]: https://ctds-planx.atlassian.net/browse/PROM-25?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: update blurb on home page

- config/gen3/crosswalk.json
- config/gen3/discovery.json
- package-lock.json
- package.json
Link to JIRA ticket if there is one: 
* updates crosswalk config
> update to 0.10.35

- config/gen3/discovery.json
Link to JIRA ticket if there is one:
> feat: add PDC

- config/gen3/crosswalk.json
Link to JIRA ticket if there is one:
> feat: update crosswalk config

- package-lock.json
- package.json
Link to JIRA ticket if there is one: 
* enable crosswalk table pagination/sorting
* widen input textArea
* remove extra column in copy/download
> Update to Gen3.2 v0.10.36

- config/gen3/discovery.json
> revert charts section

- config/gen3/discovery.json
Link to JIRA ticket if there is one: [PROM-172](https://ctds-planx.atlassian.net/browse/PROM-172)
- Add data commons chart
[PROM-172]: https://ctds-planx.atlassian.net/browse/PROM-172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (PROM-172): Add data commons chart

- config/gen3/navigation.json
- next.config.js
Link to JIRA ticket if there is one: [PROM-177](https://ctds-planx.atlassian.net/browse/PROM-177)
- add file redirect
- update navigation link
[PROM-177]: https://ctds-planx.atlassian.net/browse/PROM-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (PROM-177): add file redirect, update link

- config/gen3/discovery.json
Link to JIRA ticket if there is one: [PROM-183](https://ctds-planx.atlassian.net/browse/PROM-183)
* add synthetic column, needs this PR https://github.com/uc-cdis/cdis-manifest/pull/8293
[PROM-183]: https://ctds-planx.atlassian.net/browse/PROM-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add synthetic column

- config/gen3/discovery.json
Link to JIRA ticket if there is one: [PROM-182](https://ctds-planx.atlassian.net/browse/PROM-182)
update Discovery table to use prometheus Global ID collumn
[PROM-182]: https://ctds-planx.atlassian.net/browse/PROM-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PROM-182: update Discovery table to use prometheus Global ID collumn

- config/gen3/discovery.json
Link to JIRA ticket if there is one: 
* adds subject_cancer_grade to search
> update discovery config adding subject_cancer_grade to searchFields

- config/gen3/discovery.json
Link to JIRA ticket if there is one: [PROM-201](https://ctds-planx.atlassian.net/browse/PROM-201)
- Change the chart title from 'Gender' to 'Biological Sex'
[PROM-201]: https://ctds-planx.atlassian.net/browse/PROM-201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (PROM-201): Change the chart title from 'Gender' to 'Biological Sex'

- config/gen3/landingPage.json
Link to JIRA ticket if there is one: [PROM-231](https://ctds-planx.atlassian.net/browse/PROM-231)
- Change blurb for Home Page 
[PROM-231]: https://ctds-planx.atlassian.net/browse/PROM-231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (PROM-231): Change blurb for PDP

- config/gen3/analysisTools.json
Link to JIRA ticket if there is one:
> removing the crosswalk app icon from the analysis tab

- config/gen3/crosswalk.json
- config/gen3/login.json
Link to JIRA ticket if there is one: [PROM-284](https://ctds-planx.atlassian.net/browse/PROM-284)
- change platform name on the crosswalk
- change text on login page
[PROM-284]: https://ctds-planx.atlassian.net/browse/PROM-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (PROM-284): change platform name on the crosswalk

- config/gen3/discovery.json
Link to JIRA ticket if there is one: [PROM-289](https://ctds-planx.atlassian.net/browse/PROM-289)
- remove prometheus label
[PROM-289]: https://ctds-planx.atlassian.net/browse/PROM-289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (PROM-289): remove prometheus label

- config/gen3/discovery.json
Link to JIRA ticket if there is one: [MC2DP-321](https://ctds-planx.atlassian.net/browse/MC2DP-321)
- change charts on discovery page 
[MC2DP-321]: https://ctds-planx.atlassian.net/browse/MC2DP-321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (MC2DP-321): change charts on discovery page 

- config/gen3/discovery.json
Link to JIRA ticket if there is one: [MC2DP-321](https://ctds-planx.atlassian.net/browse/MC2DP-321)
- change charts on discovery page 
[MC2DP-321]: https://ctds-planx.atlassian.net/browse/MC2DP-321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (MC2DP-321): change charts on discovery page

- config/gen3/navigation.json
- src/pages/DataConnections.tsx
Link to JIRA ticket if there is one: [MC2DP-405](https://ctds-planx.atlassian.net/browse/MC2DP-405) [MC2DP-402](https://ctds-planx.atlassian.net/browse/MC2DP-402)
- Hide Discovery tab in Prod and QA
- Change Data Connection page numbers from 100/100 to 87/87 for GDC- apollo luad-genomics entry
[MC2DP-405]: https://ctds-planx.atlassian.net/browse/MC2DP-405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MC2DP-402]: https://ctds-planx.atlassian.net/browse/MC2DP-402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (MC2DP-402 MC2DP-405): small fixes

- config/gen3/explorer.json
Link to JIRA ticket if there is one: [MC2DP-412](https://ctds-planx.atlassian.net/browse/MC2DP-412)
- Explorer Column renaming
[MC2DP-412]: https://ctds-planx.atlassian.net/browse/MC2DP-412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (MC2DP-412): Explorer Column renaming

- config/gen3/explorer.json
> update explorer global id

- config/gen3/explorer.json
Link to JIRA ticket if there is one: [MC2DP-419](https://ctds-planx.atlassian.net/browse/MC2DP-419) [MC2DP-420](https://ctds-planx.atlassian.net/browse/MC2DP-420)
- Remove some data sources from data commons filter
- "Data Commons" field is empty for TCIA and VMOAT
[MC2DP-419]: https://ctds-planx.atlassian.net/browse/MC2DP-419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MC2DP-420]: https://ctds-planx.atlassian.net/browse/MC2DP-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (MC2DP-420 MC2DP-419): small fixes

- config/gen3/explorer.json
Link to JIRA ticket if there is one: [MC2DP-421](https://ctds-planx.atlassian.net/browse/MC2DP-421)
- add commons id label
- add commons id to details view  
[MC2DP-421]: https://ctds-planx.atlassian.net/browse/MC2DP-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (MC2DP-421): add commons id

- src/pages/DataConnections.tsx
Link to JIRA ticket if there is one: 
- Change Data Connections page data
> Change Data Connections page data
